### ISSUE TITLE
.

### ISSUE THREAD

**Issue by shaun-ba** [danthem/undelete-btrfs#6]
.

**Comment by danthem** [comment]
Hi Shaun,
That doesn't sound right - but I do have a limitation listed in the readme stating:
> *Does not play well in systems where readarray does not take the -d flag

It's been a while since I wrote this but I remember coming across one system where this was preventing me from automatically generating the regex with the current script.. (yes.. I do intend to some day find a better solution)

As for having overwritten the file in question, that's clearly problematic and my script, like the other one you used, would likely just recover the new and "incorrect" file. However, you may be able to manually find an older copy of the file.. Now bear in mind that my terminology on BTRFS is a bit rusty as I've not needed to do any recovery on btrfs myself for a long time but:

What you need to do is get `btrfs-find-root` and dump all output to a file, like so:
`btrfs-find-root &> /tmp/findroots.out`
then filter out the relevant info :
 `grep -a Well /tmp/findroots.out |  sed -r -e 's/Well block ([0-9]+).*/\1/' | sort -rn > /tmp/roots.out`

This will give you a list of "roots" (I call them this but t may not be the 'official' terminology).. These can be passed to the `btrfs restore` command with the `-t` flag.. The higher the number, the more recent.. So you might want to start with the highest number and work your way back.. Hopefully one will contain the data you are looking for. Remember to empty the destination dir after each attempt as it may otherwise skip the file.

example:
`btrfs restore -iv -t 12321432 --path-regex='^/(|home(|/username(|/Desktop(|/.*))))$' /dev/md2 /data/restored_backup`
(I'll also add that I'm not completely if writing the regex like this is as important nowadays or if it's more accepting of a "cleaner" way of writing it.. Check up to date btrfs docs).


Hope you find what you're looking for!

/Dan
