### ISSUE TITLE
Files not restored

### ISSUE THREAD

**Issue by NebulaBC** [danthem/undelete-btrfs#7]
Just recently, I had an incident where I deleted import files. I use BTRFS, so first thing I did was boot a live USB. The files appeared in BTRFS undelete (and I gave it the OK to restore), but when I mounted the drive to look for the files, they were nowhere to be found. Now BTRFS undelete can not even find them anymore to restore. My files are probably gone for good now, but I am curious why it did not save the files, I checked the live usb’s file system and the drive that the files were being restored from.

**Comment by quayilab** [comment]
Hi, I think I can share my successful experience in using this script. 
I have a directory 'storage' within my home dir, which is a mount of a dedicated partition (separated from the home). 
- I had an incident which deleted my files in 'storage/data' (7+ GB)
- I run the script as instructed, and I can see the script found my deleted files (depth 2) in stdout
- I restored the files
- I checked in /mnt/, yes, they exist there.
- I randomly checked the file content, seems to be okay
- I thought /mnt/ is where my 'storage' was mounted, so I quitted the script and check the 'storage/data', none was restored.
- I tried again, and found out that /mnt/ was a different storage where I can copy the restored files from, to my 'storage/data' (after it being mounted)
- I mount the partition to my home (/home/me/storage) and copy those restored file from /mnt/ to original path. 
- Done

so, from your case, I think those found files are located in your live USB /mnt/, not in your original drive, you have to copy them to your original drive. Since it's a live USB, they won't stay there and you need to redo the steps again.
Hope this helps.

I'd like to say a huge thank to the author @danthem who create this script that had been a savior of my months work!

**Comment by NebulaBC** [comment]
> Hi, I think I can share my successful experience in using this script. I have a directory 'storage' within my home dir, which is a mount of a dedicated partition (separated from the home).
> 
> * I had an incident which deleted my files in 'storage/data' (7+ GB)
> * I run the script as instructed, and I can see the script found my deleted files (depth 2) in stdout
> * I restored the files
> * I checked in /mnt/, yes, they exist there.
> * I randomly checked the file content, seems to be okay
> * I thought /mnt/ is where my 'storage' was mounted, so I quitted the script and check the 'storage/data', none was restored.
> * I tried again, and found out that /mnt/ was a different storage where I can copy the restored files from, to my 'storage/data' (after it being mounted)
> * I mount the partition to my home (/home/me/storage) and copy those restored file from /mnt/ to original path.
> * Done
> 
> so, from your case, I think those found files are located in your live USB /mnt/, not in your original drive, you have to copy them to your original drive. Since it's a live USB, they won't stay there and you need to redo the steps again. Hope this helps.
> 
> I'd like to say a huge thank to the author @danthem who create this script that had been a savior of my months work!

I used the find command and could not find the files on the usb or original drive. I have had success with this in the past, but at that time after “successfully” restoring and the files not showing up, the script could no longer restore the files at all.

**Comment by danthem** [comment]
I think @quayilab is on the right track here that files may have been recovered to a path on the live USB meaning that they would have been lost upon a reboot.  Keep in mind that when you live boot from USB it will run the OS  in memory and if you want to keep files you'd have to mount some kind of persistent storage and recover to there.

It does seems strange that first attempt at recovery found files but not the second, I wonder if there was some minor difference in how the path was written? An accidental space at the end or something? the find-roots and restore does not in any way touch/modify the filesystem so if it worked the first time it should have worked the second. One possibility would be if the filesystem had been mounted again in between the tries, at which point the OS may have done something to it.

I realize this issue is quite old and at this point we can only speculate what happened. Will close this issue since we can't know what happened and I don't see any actionable task. If you come across a similar issue in the future please let me know.

FYI I am working on some improvements and also a 'full volume' restore option... Not sure when they'll be ready but hopefully soon™.
